# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ashwani P Rao 
description: > #
I am Software development engineer at Amazon with strong in Machine Learning and Information
retrieval. I have worked on statistical information retrieval models, machine learning
applications on electronic health records, customer query logs, big data technoligies 
such as hadoop, spark, .....That's enough for now.

email: ashwamegh1935@gmail.com

#description: > # this means to ignore newlines until "baseurl:"
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.

baseurl: "/index.html" # the subpath of your site, e.g. /blog
url: "http://rumpelt.github.io" # the base hostname & protocol for your site
#twitter_username: 
github_username:  rumpelt

# Build settings
markdown: kramdown
